name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout edk2
        uses: actions/checkout@v2
        with:
          repository: tianocore/edk2
          ref: edk2-stable202411
          path: edk2
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential uuid-dev iasl git gcc-aarch64-linux-gnu gcc-aarch64-linux-gnu

      - name: Build
        run: export GCC5_AARCH64_PREFIX=aarch64-linux-gnu- && make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Reboot2Android
          path: edk2/Build/Reboot2AndroidPkg/RELEASE_GCC5/AARCH64/Reboot2AndroidPkg/Application/Reboot2Android/Reboot2Android/OUTPUT/Reboot2Android.efi
      
      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.2
          files: edk2/Build/Reboot2AndroidPkg/RELEASE_GCC5/AARCH64/Reboot2AndroidPkg/Application/Reboot2Android/Reboot2Android/OUTPUT/Reboot2Android.efi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
